WebDevelopment/SiT.WebDevelopmentDemo/Controllers/NotesController.cs
using Microsoft.AspNetCore.Mvc;
using SiT.WebDevelopmentDemo.Core.Interfaces;
using SiT.WebDevelopmentDemo.Data.Models;
using SiT.WebDevelopmentDemo.ViewModels;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace SiT.WebDevelopmentDemo.Controllers
{
    [Route("notes")]
    public class NotesController : Controller
    {
        private readonly INoteService _noteService;

        public NotesController(INoteService noteService)
        {
            this._noteService = noteService ?? throw new ArgumentNullException(nameof(noteService));
        }

        [HttpGet("[action]")]
        public async Task<IActionResult> GetAllNotes(CancellationToken cancellationToken)
        {
            var notes = await this._noteService.GetAllNotesAsync(cancellationToken);
            return this.View(notes);
        }

        [HttpGet("[action]")]
        public IActionResult Create() => this.View();

        [HttpPost("[action]")]
        public async Task<IActionResult> Create(CreateNoteInputModel inputModel, CancellationToken cancellationToken)
        {
            var note = new Note
            {
                Text = inputModel.Text,
                Theme = inputModel.Theme
            };
            await this._noteService.CreateAsync(note, cancellationToken);
            return this.RedirectToAction(nameof(this.GetAllNotes));
        }
    }
}

WebDevelopment/SiT.WebDevelopmentDemo/Views/Notes/Create.cshtml
@model SiT.WebDevelopmentDemo.ViewModels.CreateNoteInputModel

<div>
    <form method="post" asp-controller="Notes" asp-action="Create">
        <div>
            <label asp-for="Theme"></label>
            <input asp-for="Theme" />
        </div>

        <div>
            <label asp-for="Text"></label>
            <textarea asp-for="Text"></textarea>
        </div>

        <div>
            <button class="btn btn-primary" type="submit">Create note</button>
        </div>
    </form>
</div>

WebDevelopment/SiT.WebDevelopmentDemo/Views/Notes/GetAllNotes.cshtml
@model IEnumerable<SiT.WebDevelopmentDemo.Data.Models.Note>

<a class="btn btn-primary" asp-controller="Notes" asp-action="Create">Create</a>
<table>
    <thead>
        <tr>
            <th>
                Theme
            </th>
            <th>
                Text
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var modelNote in this.Model)
        {
            <tr>
                <td>
                    @modelNote.Theme
                </td>

                <td>
                    @modelNote.Text
                </td>
            </tr>
        }
    </tbody>
</table>